# Site settings
baseurl = "/"
languageCode = "en-us"
title = "100 Days of Code"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "100 Days of Code"
    subtitle = "I've joined the #100DaysOfCode Challenge."
    author = "Thomas Phillips"
    description = "Daily code journal for my projects."
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts, 100 days of code, #100daysofcode, #100DaysOfCode"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Link to Work"

    # Footer text
    footertext = "[Check me out on GitHub](https://github.com/thomasphillips3)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']

# Pagination
paginate = 10
paginatePath = "page"
