backend:
  name: git-gateway
  # name: test-repo
  branch: master

# publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "code"
    label: "Day of code"
    tags: [""]
    folder: "data/days"
    create: true
    slug: "Day_{{day}}-{{slug}}"
    extension: "toml"
    fields:
      - { label: "Day", name: "day", widget: "number" }
      - { label: "Title", name: "title", widget: "string", default: "Day " }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Today's Progress", name: "description", widget: "markdown"}
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Thumb", name: "thumb", widget: "image", required: false }
      - { label: "Alt text", name: "alt", widget: "string", required: false }
      - { label: "Link to Work", name: "url", widget: "string", default: "https://github.com/thomasphillips3/100-days-of-code" }
      - { label: "Tags", name: "tags", widget: "list", default: ["100daysofcode"], required: false }
